src/web.rs
* Modified pathing on web.rs to work with /graphql and any other paths working with /graphql
* \
```sh
❯ curl 'http://127.0.0.1:8080' \
-X POST\
-H 'content-type: application/json' \
--data '{
"query": "{ issues }"
}'
```
* \graphql
```sh
❯ curl 'http://127.0.0.1:8080/graphql' \
-X POST\
-H 'content-type: application/json' \
--data '{
"query": "{ issues }"
}'
{"data":{"issues":[]}}%  
```
* \graphql\5
```sh
❯ curl 'http://127.0.0.1:8080/graphql/5' \
-X POST\
-H 'content-type: application/json' \
--data '{
"query": "{ issues }"
}'
{"data":{"issues":[]}}%  
```
=> Modify paths to work on /graphql

src/conf.rs, src/main.rs
Since it is used in `main` only, there is no need to place it in a
different module and make it `pub`.
Also the constant has been renamed `USAGE` for readability.
=> Make the usage string private

src/conf.rs, src/main.rs
This change shortens `main` and thus `allow(clippy::too_many_lines)`
is no longer necessary.
=> Separate command-line parsing from `main`

src/database.rs, src/graphql.rs
In [Getter names follow Rust convention (C-GETTER)](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter):
> With a few exceptions, the `get_` prefix is not used for getters in Rust code.
=> Rename functions that don't follow Rust API Guidelines

src/database.rs, src/graphql.rs
Functions names (`select_issue_range` and `select_pr_range`) implies
what `Tree` each function should use, and thus there is no need to
pass the `Tree` as an argument.
=> Remove redundant argument

src/graphql.rs
async-graphql converts a function name to CamelCase automatically.
=> Remove unnecessary `allow(non_snake_case)`

src/graphql.rs, src/web.rs
This allows to change the GraphQL schema (e.g., adding mutations) without modifying web.rs.
=> Decouple web module from graphql

.markdownlint.yaml, CHANGELOG.md, Cargo.lock, Cargo.toml, src/checkout.rs, src/github.rs, src/google.rs, src/main.rs
As a server, github-dashboard-server doesn't always have a terminal where an administrator monitors. Besides, the administrator may want to filter messages according to the level of severity (e.g., warnings, errors, informational messages, etc). The tracing crate provides finer-grained ways to collect diagnostic inforamtion from an application.
=> Use tracing to print messages

src/database.rs, src/main.rs
Using a more concrete type like [`Path`](https://doc.rust-lang.org/std/path/struct.Path.html) rather than a general type like `str` makes the intention of the code clearer.
=> Use `Path` to represent a path

src/graphql.rs
Functions for async-graphql queries don't need to be public.
=> Remove unnecessary `pub`

CHANGELOG.md, src/database.rs
Returning a proper error message is better than returning a fake data or panicking.
=> Handle invalid data in the database

src/graphql.rs, src/graphql/issue.rs, src/graphql/pull_request.rs
테스트 데이터를 unit test 내에서 직접 추가하고, GraphQL API의 응답을 JSON 레벨에서 직접 비교해서 동작 여부를 테스트합니다.
테스트 코드때문에 graphql모듈의 라인 수가 늘어나서 issue와 pull_request 두개의 submodule로 분리했습니다.
=> Add unit tests for GraphQL API `issues` and `pullRequests`

CHANGELOG.md, src/database.rs, src/graphql.rs
This limits the number of connections when neither `first` nor `last` is provided. Returning all the avaialbe issues/pull requests should be avoided because it might cause too much burden on the server or network.
=> Set default page size

src/google.rs, src/graphql/issue.rs, src/graphql/pull_request.rs
Closes #108
Corrected mismatched parentheses and braces to to resolve delimiter-related Clippy warnings.
=> Fix clippy errors

.github/workflows/ci.yml, src/checkout.rs, src/conf.rs, src/database.rs, src/github.rs, src/graphql.rs, src/main.rs, src/web.rs
Closes #109
- Added `cargo fmt -- --check --config group_imports=StdExternalCrate` to `ci.yml` to enforce standardized import grouping. 
- Reformatted source files to comply with this rule.
=> Enforce import grouping in formatting checks

.github/workflows/ci.yml
Closes #128
- Bumped codecov/codecov-action from v2 → v5
- Added `fail_ci_if_error: true` to the Codecov action
- ensures the CI fails if coverage upload fails.
- Bumped actions/checkout from v2 → v4
=> Update codecov-action to latest version

CHANGELOG.md, src/conf.rs, src/main.rs
closes #120
- `db_name`이 아닌 `db_path` 를 참조하도록 수정했습니다.
=> Fix config parsing to db_path instead of db_name

src/checkout.rs, src/conf.rs, src/database.rs, src/github.rs, src/google.rs, src/graphql.rs, src/graphql/issue.rs, src/graphql/pull_request.rs, src/web.rs
Closes #121
다음과 같은 기조로 접근자를 변경했습니다.
clippy 상으로 unnecessary pub access 진단이 나오는 코드 중,
1. parent mod에서만 사용되고 있어 pub(super)를 적용가능한 함수 / 모듈은 전부 pub(super) 적용
2. 반대로 crate 내부에서 참조되고 있는 코드들은 pub(crate) 적용.
3. 그 외에 #[allow(unused)] 매크로가 사용되었거나 crate 내부 참조가 없는 코드는 pub을 삭제했습니다.
=> Minimize unnecessary pub access modifiers

CHANGELOG.md, README.md, src/checkout.rs
- Close #127
- Implemented support for SSH passphrase using the `SSH_PASSPHRASE` environment variable.
- Set the SSH passphrase using the following command:
```bash
export SSH_PASSPHRASE="your_passphrase"
```
- If not set, the program will proceed without it.
- Updated README with instructions on setting the SSH passphrase.
- Modified Changelog to reflect the new feature.
=> Support SSH passphrase via environment variable

src/checkout.rs
Modified error handling in `username_from_url` by explicitly providing a default value of `"git"` using `unwrap_or` instead of `expect`.
This change prevents potential issues that could arise if `REMOTE_BASE_URL` is modified. Explicitly using `"git"` ensures consistent behavior independent of the string constant's value.
Close: #164
=> Refactor improper `expect` to `unwrap_or`

CHANGELOG.md, Cargo.toml, src/database.rs, src/github.rs, src/github/issues.graphql, src/graphql.rs, src/graphql/issue.rs, src/graphql/issue_stat.rs
=> Add `issueStat` query and `openIssueCount` field

CHANGELOG.md, src/database.rs, src/database/discussion.rs, src/github.rs, src/github/discussions.graphql, src/graphql.rs, src/graphql/discussion.rs
- close #171 
GitHub로부터 `Discussion` 데이터를 가져와 저장하는 기능을 구현했습니다.
기존 코드의 구조를 참고하되, 역할에 따라 파일을 분리하여 가독성과 유지보수성을 높였습니다.
현재 `GraphQL` 쿼리는 `Discussion`의 모든 필드를 포함하고 있지 않습니다.
- `database/discussion.rs` : DB에 저장될 스키마 구조체 정의
- `graphql/discussion.rs` : GitHub Dashboard에서 제공하는 GraphQL API 응답 구조체 정의
=> Add Discussions GraphQL query

CHANGELOG.md, src/api/pull_request.rs, src/database.rs, src/outbound.rs, src/outbound/graphql/pull_requests.graphql
Closes #170
- Added new fields (specified in #170) to the `PullRequests` GraphQL query.
- Extended `GitHubPullRequests` to store the additional data.
- Implemented support for nested types like labels, comments, reviews, and commits.
- Derived `Serialize`/`Deserialize` for new types to enable database storage.
=> Add new fields to `PullRequests` query

src/api/issue.rs, src/api/issue_stat.rs, src/database.rs, src/database/issue.rs, src/outbound.rs
- ___OBJECTIVE___: Convert GitHub API Response to our own struct `GitHubIssue` using `From<T>` or `TryFrom<T>`
- Define `struct GitHubIssueResponse` and implement `TryFrom<T>` to parse GitHub API response.
* ___From___: GitHub API response
* ___To___: `struct GitHubIssueResponse` defined by us
* If request is wrong, `try_from` returns `Err`. If empty response, `try_from` returns `Ok(GitHubIssueResponse)`.
- Implement `From<T>` to convert types
* ___From___: `struct`s which is generated by `async-graphql`'s codegen based on GitHub GraphQL schema (ex) `crate::github::issues::ResponseData`, `crate::github::issues::IssuesRepositoryIssuesNodesComments`, ...
* ___To___: Our own `struct`s (ex) `GitHubIssue`, `GitHubCommentConnection`, ...
* Since wrong request or bad response will be handled by …
=> Add conversion for GitHub API response to `GitHubIssue`

CHANGELOG.md, src/api/issue.rs, src/api/issue_stat.rs, src/database/issue.rs, src/outbound.rs, src/outbound/graphql/issues.graphql
- 2개의 GraphQL Query 를 구현함: `resolvedIssues`, `resolvedIssueStat`
- Resolved Issue 기준
* 현재 명확히 합의된 Resolved Issue 의 기준은 없음.
* 현재 구현에서는 PR 이 연결되어 auto-closed 된 issue 들만 추적함. 이슈 자신의 상태가 closed 이고, 연결된 PR 들의 상태가 모두 merged 인 이슈를 resolved issue 로 판단함. manually closed issue 중 어떤 것들을 resolved issue 로 판단할지는 추후 논의 예정
- Resolved Issue Statistics
* 4가지 통계를 제공: `totalCount`, `latest`, `latestUpdated`, `latestClosed`
* 논의 후 의미있는 통계를 추가하는 것이 필요해보임
- 구현한 2개의 GraphQL Query 들은 아래 쿼리들을 이용하여 테스트 했습니다.
```graphql
query ResolvedIssues(
$repo: String
$after: String
$before: String
$first: Int
$last: Int
) {
resolvedIssues(
after: $after
before: $before
first: $first
last: $last
filter: { repo: $repo }
) {
totalCount
pageInfo {
startCursor
endCursor
hasPreviousPage
hasNextPage
}
edges {
cursor
node {
repo
owner …
```
=> Add statistics for resolved issues

CHANGELOG.md, src/api.rs, src/api/pull_request_stat.rs
- Close #222
- Description
- Implement `Sub` trait for `DateTimeUtc` to calculate day difference
- The following code did not work as expected for reasons I couldn’t identify. Therefore, I implemented the functionality as shown in this PR.
```rust
fn sub(self, rhs: Self) -> Self::Output {
self.0.sub(rhs.0).get_days()
}
```
=> Add average days to merged PRs

CHANGELOG.md, src/api.rs, src/api/issue.rs, src/api/issue_stat.rs
=> Add `avgResolutionDays` to issueStat query
