Cargo.lock, Cargo.toml, README.md, src/conf.rs, src/main.rs, src/web.rs
feat :
-Read config toml file
-Set Web address
fix:
-add 1 arg : web::serve function
=> Fixes #6:read config toml file/set web address

Cargo.lock, Cargo.toml, src/graphql.rs, src/main.rs, src/web.rs
=> Add GraphQL API #10

.github/workflows/ci.yml
저장소로 push하거나 PR을 생성할 때마다 다음 명령을 수행하여 이상이 없는지 검사합니다.
* cargo fmt
* cargo clippy
* cargo build
* cargo test
=> GitHub Actions를 이용한 CI 설정

README.md, src/conf.rs, src/main.rs
Added version with package 
Close #12
=> Added version option -V

.github/workflows/ci.yml, README.md
This also fixes markdownlint errors in README.md.
=> Run markdownlint in CI

README.md, src/conf.rs, src/main.rs
=> Print Usage

README.md, src/conf.rs, src/github.rs, src/main.rs
- Fix send_github_query function,Config struct
- Add README.md contents(about token)
Resolves: #26
=> Add User_Agent Header

README.md, src/web.rs
Changes:
- web.rs
- README.md
to run `http://127.0.0.1/graphql/playground`
Close #31
=> Add Playground #31

src/graphql.rs
-Add Issue struct
-Modify isseues function
Resolves : #33
=> Modify issues return type

Cargo.lock, Cargo.toml, README.md, src/conf.rs, src/database.rs, src/github.rs, src/main.rs, src/open_issues.graphql
- Add db functions (insert/delete/select)
- Modify config struct/README.md (about sled database)
- Modify query (get number/title)
Resolves: #29
=> Add key-value storage function

src/database.rs, src/graphql.rs, src/main.rs
=> Return issues value

Cargo.toml, src/database.rs, src/main.rs
=> Send query every hour

Cargo.lock, Cargo.toml, src/database.rs, src/main.rs
=> Add owner name key

README.md, src/conf.rs, src/github.rs, src/main.rs
=> Add more repos

src/database.rs, src/graphql.rs
=> Modify pagination logic

Cargo.lock, Cargo.toml, README.md, src/main.rs
=> Read default config file

src/github.rs, src/open_issues.graphql
=> Fetch all github issue

src/database.rs, src/github.rs, src/graphql.rs, src/main.rs, src/open_issues.graphql, src/pull_requests.graphql
=> Add PullRequests

src/pull_requests.graphql
=> Add assignees

src/database.rs, src/github.rs
=> Insert assignees data to the storage

src/database.rs, src/google.rs, src/main.rs
* get google public key
* compare current key (if exists) and if not the same, delete and reinsert the google key
* if key does not exist, insert key into the root tree
=> Get Google's public key

README.md, src/conf.rs, src/github.rs, src/main.rs
=> Supports multiple users

README.md, src/database.rs, src/graphql.rs
=> Add 'assignees' for 'pullRequest' query

src/github.rs, src/main.rs
`main` doesn't have to know the internal implementation of fetching
issues and PRs from GitHub.
=> Simplify github module's interface

src/database.rs, src/github.rs, src/graphql.rs, src/pull_requests.graphql
=> Get 'reviewers' data

Cargo.lock, Cargo.toml, README.md, src/checkout.rs, src/conf.rs, src/github.rs, src/main.rs
=> Checkout remote codes

Cargo.lock, Cargo.toml, README.md, src/conf.rs, src/main.rs, src/web.rs
=> Support to https

src/github.rs, src/main.rs
=> Retry TCP timeout

src/database.rs
=> Remove duplicate codes in parsing database keys

README.md, src/database.rs, src/graphql.rs, src/main.rs
=> refactoring database module

src/database.rs, src/github.rs, src/graphql.rs, src/open_issues.graphql
=> Add author information to storage

src/database.rs, src/github.rs, src/graphql.rs
There were mixed uses of "PR" and "pull request".
=> Spell pull request consistently

src/github.rs
- when running the server after git repositories are pulled,
In the 2th issue loop, the issue could not be fetch due to the time condition.
So, I changed location of last_time to the top of the loop.
=> Change last_time code location

src/database.rs, src/github.rs, src/open_issues.graphql
=> Return unclosed issue

src/graphql.rs
GraphQL API 함수들(`conn_raw_events`, `log_raw_events` 등)의 리턴 타입이 `anyhow::Error`로 되어 있는데, 이건 애플리케이션에서 아무 에러나 다룰 수 있게 한다는 점에서는 좋지만 JSON으로 바뀌어 전송되는 GraphQL에서는 그다지 유용하지 못합니다. GraphQL 클라이언트쪽에서 쉽게 에러메시지를 볼 수 있도록 `async_graphql::Error`를 리턴하는 것이 좋습니다. `async_graphql::Error`는 `pub` 필드로 `message`란 항목이 있어서 JSON으로 변환되더라도 에러메시지가 명시적으로 드러납니다.
`load_issues`, `load_pull_requests`를 closure 밖으로 뺀 것은 두 함수가 공통부분이 많아서 추후 리팩터링을 하는게 좋을 것 같은데, 그 때 변경을 용이하게 하기 위해서입니다.
=> Use async-graphql's `Result` rather than `anyhow::Result`

src/graphql.rs
=> Modify empty response

CHANGELOG.md, src/database.rs, src/graphql.rs, src/graphql/issue.rs, src/graphql/pull_request.rs
* Merged duplicate pagination code in issues and pull requests.
* The `database` module no longer exposes sled in its `pub` interfaces.
=> Refactor pagination

README.md
closes #124 
- fine-grained token
- required permissions
=> Add token requirements to README

README.md, src/main.rs
=> Rename 'einsis' to 'cluml'

src/checkout.rs, src/github.rs
- Safe guaranteed cases replaced with `expect()` and rationale provided.
- Non-guaranteed cases handled explicitly with `context()` or bypassed when appropriate.
Test code intentionally excluded from changes.
Close: #135
=> Replace `unwrap` with proper error handling

README.md
=> Refactor README to add configuration sections

src/main.rs
=> Refactor settings error handling

CHANGELOG.md, src/api.rs, src/api/discussion.rs, src/api/discussion_stat.rs, src/api/issue_stat.rs, src/database/discussion.rs
=> Add statistics for discussion

Cargo.lock, Cargo.toml, README.md, src/database.rs, src/database/discussion.rs, src/main.rs, src/outbound.rs
=> Replace `sled` with `fjall`

.github/workflows/ci.yml
=> Update `actions/checkout` to v5

src/api/pull_request.rs, src/api/pull_request_stat.rs, src/database.rs, src/database/pull_request.rs, src/outbound.rs
=> Extract pull request structs
